title: auto-uv-env
description: Automatic UV-based Python virtual environment management
url: https://auto-uv-env.ashwch.com
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

# Remove theme as we're using custom layouts
# theme: minima

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - serve-local.sh
