name: Build Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-deb:
    name: Build Debian Package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y debhelper devscripts

    - name: Build Debian package
      run: |
        # Create debian directory structure
        mkdir -p debian
        cp packaging/debian/control debian/

        # Create debian/rules
        cat > debian/rules << 'EOF'
        #!/usr/bin/make -f
        %:
        	dh $@

        override_dh_auto_install:
        	install -D -m 755 auto-uv-env $(DESTDIR)/usr/bin/auto-uv-env
        	mkdir -p $(DESTDIR)/usr/share/auto-uv-env
        	install -m 644 share/auto-uv-env/* $(DESTDIR)/usr/share/auto-uv-env/
        EOF
        chmod +x debian/rules

        # Create changelog
        cat > debian/changelog << EOF
        auto-uv-env (${GITHUB_REF#refs/tags/v}) unstable; urgency=low

          * Release ${GITHUB_REF#refs/tags/}

         -- Ashwini Chaudhary <ashwch@example.com>  $(date -R)
        EOF

        # Build package
        debuild -us -uc -b

    - name: Upload Debian package
      uses: actions/upload-artifact@v3
      with:
        name: debian-package
        path: ../*.deb

  build-rpm:
    name: Build RPM Package
    runs-on: ubuntu-latest
    container: rockylinux:9

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        dnf install -y rpm-build rpmdevtools

    - name: Setup RPM build tree
      run: |
        rpmdev-setuptree
        cp packaging/rpm/auto-uv-env.spec ~/rpmbuild/SPECS/
        tar czf ~/rpmbuild/SOURCES/auto-uv-env-${GITHUB_REF#refs/tags/v}.tar.gz --transform "s,^,auto-uv-env-${GITHUB_REF#refs/tags/v}/," .

    - name: Build RPM
      run: |
        rpmbuild -ba ~/rpmbuild/SPECS/auto-uv-env.spec

    - name: Upload RPM packages
      uses: actions/upload-artifact@v3
      with:
        name: rpm-packages
        path: ~/rpmbuild/RPMS/noarch/*.rpm

  create-release:
    name: Create Release with Packages
    needs: [build-deb, build-rpm]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          debian-package/*.deb
          rpm-packages/*.rpm
        body: |
          ## Installation

          ### Debian/Ubuntu
          ```bash
          wget https://github.com/ashwch/auto-uv-env/releases/download/${{ github.ref_name }}/auto-uv-env_${GITHUB_REF#refs/tags/v}_all.deb
          sudo dpkg -i auto-uv-env_${GITHUB_REF#refs/tags/v}_all.deb
          ```

          ### RHEL/Fedora/CentOS
          ```bash
          wget https://github.com/ashwch/auto-uv-env/releases/download/${{ github.ref_name }}/auto-uv-env-${GITHUB_REF#refs/tags/v}-1.noarch.rpm
          sudo rpm -i auto-uv-env-${GITHUB_REF#refs/tags/v}-1.noarch.rpm
          ```

          ### Install Script
          ```bash
          curl -sSL https://raw.githubusercontent.com/ashwch/auto-uv-env/main/scripts/install.sh | bash
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
